name: finace_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: ^3.5.4

dependencies: 
  cupertino_icons: ^1.0.8
  get: 4.6.6
  flutter: 
    sdk: flutter
  intl: ^0.18.0
  syncfusion_flutter_charts: ^20.4.38
  sqflite: ^2.0.0+3
  path: ^1.8.1
  flutter_swiper_view: ^1.1.8

dev_dependencies: 
  flutter_lints: 5.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

